baseURL = "https://example.com/blog"
title = "ゆのゆのルーム"
author = "ゆのゆの"
copyright = "ゆのゆの"
pagination.pagerSize = 10
languageCode = "jp"
defaultContentLanguage = 'jp'
theme = "tailwind"

[markup]
  _merge = "deep"

[params]
  contentTypeName = "posts"
  

  [params.header]
    logo = "logo.jpeg"
    title = "ゆのゆのルーム"

  [params.footer]
    poweredby = true

[menu]

  [[menu.main]]
    identifier = "post"
    name = "投稿"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[module]
  [[module.imports]]
    path = "github.com/tomowang/hugo-theme-tailwind"

[[social_media.items]]
enabled = false
title = 'Facebook'
icon = 'brand-facebook'
link = 'https://www.facebook.com/'